/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllCount: typeof import('./src/components/timer/all-count.vue')['default']
    BadUse: typeof import('./src/components/modal/bad-use.vue')['default']
    Body: typeof import('./src/components/dialog/body.vue')['default']
    ButtonList: typeof import('./src/components/button-list.vue')['default']
    Child: typeof import('./src/components/child.vue')['default']
    Child1: typeof import('./src/components/life-cycle/child1.vue')['default']
    Child2: typeof import('./src/components/life-cycle/child2.vue')['default']
    Child3: typeof import('./src/components/life-cycle/child3.vue')['default']
    CountdownSon: typeof import('./src/components/timer/countdown-son.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Father: typeof import('./src/components/life-cycle/father.vue')['default']
    Footer: typeof import('./src/components/dialog/footer.vue')['default']
    GoodCase: typeof import('./src/components/modal/good-case/index.vue')['default']
    Modal1: typeof import('./src/components/modal/modal-1.vue')['default']
    Modal2: typeof import('./src/components/modal/modal-2.vue')['default']
    Modal3: typeof import('./src/components/modal/modal-3.vue')['default']
    MyCountdown: typeof import('./src/components/timer/my-countdown.vue')['default']
    ProSearch: typeof import('./src/components/pro-table/pro-search.vue')['default']
    ProTable: typeof import('./src/components/pro-table/pro-table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/pro-table/search-form.vue')['default']
    UnityModal: typeof import('./src/components/modal/good-case/unity-modal.vue')['default']
    Use: typeof import('./src/components/modal/use.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
