/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Child1: typeof import('./src/components/life-cycle/child1.vue')['default']
    Child2: typeof import('./src/components/life-cycle/child2.vue')['default']
    Child3: typeof import('./src/components/life-cycle/child3.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    Father: typeof import('./src/components/life-cycle/father.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
