/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    'CacheLayout': RouteRecordInfo<'CacheLayout', '/cache', Record<never, never>, Record<never, never>>,
    '/cache/[id]/': RouteRecordInfo<'/cache/[id]/', '/cache/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cache/[id]/content': RouteRecordInfo<'/cache/[id]/content', '/cache/:id/content', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cache/[id]/over-view': RouteRecordInfo<'/cache/[id]/over-view', '/cache/:id/over-view', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cache/[id]/token': RouteRecordInfo<'/cache/[id]/token', '/cache/:id/token', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/directives': RouteRecordInfo<'/directives', '/directives', Record<never, never>, Record<never, never>>,
    '/life-cycle': RouteRecordInfo<'/life-cycle', '/life-cycle', Record<never, never>, Record<never, never>>,
    '/timer': RouteRecordInfo<'/timer', '/timer', Record<never, never>, Record<never, never>>,
  }
}
